#Aliases
alias py='python3'
alias clip='xclip -selection clipboard'
alias activate='source .venv/bin/activate'
alias gs='git status'
alias ga='git add'
alias gc='git commit -m"'
alias gp='git push'
alias ta='tmux attach || tmux new'
alias tks='tmux kill-session'
alias nv='nvim .'
alias vim='nvim'
alias espv='. /home/igorantunes/repo/esp-idf/export.sh'
alias espv2='. /home/igorantunes/repo/esp-idf-v4.3-beta1/export.sh'
alias rosv='. /opt/ros/jazzy/setup.bash'
